### ISSUE TITLE
How can I change the network into Sepolia test network? I already deployed my contracts in Sepolia.

### ISSUE THREAD

**Issue by laronlineworld** [JorisZierold/gaming-dapp-rock-paper-scissors#1]

**Comment by JorisZierold** [comment]
https://github.com/JorisZierold/gaming-dapp-rock-paper-scissors/blob/618acbb621d84d7f64139d11a8d9fee1a6074b64/app/src/main.jsx#L16

**Comment by laronlineworld** [comment]
I already change the network, but there's an error

**Comment by hupptechnologies** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mmmim24, @LinYuanzhao, @unpacked-dev, @tzabar, @pedroigorjs, @AppServiceProvider, @ravivats, @Eustatiu, @maskott, @raitd, @VijaySamrath, @AliAkhtari78, @sammyne, @mbilal0612, @zhstark, @vladchepel, @zhaoyulong, @ibaxio, @haind146, @igorantun, @peoplewhite, @riccoyu, @ihao, @old-adapdr, @li-rh, @hood, @AI666666, @bamboo321, @xuboso, @rajdeepmondal1, @ajperezc, @antifran, @clarissawatson, @twopieare, @TeavenX, @Emerson-Portugal, @AJTrading, @mingz2013, @ConorWadsworth, @ilaykut, @mthli, @Panda666-del, @sklinkert, @tahtaciburak, @dofstar, @franjsco, @tsvillain, @Aman-kinger, @topc000, @PBMocha
